#!/bin/bash

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=${JAVA_HOME}/bin:${PATH}


JAVA_OPTS=-Djava.awt.headless=true

cd ${OPENSHIFT_REPO_DIR}
java ${JAVA_OPTS} -jar build/libs/*-standalone.jar -s MongoDb -a ${OPENSHIFT_DIY_IP} -p 8080 |& /usr/bin/logshifter -tag snippets &
