language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
env:
  - TERM=dumb
before_script:
  - chmod +x gradlew deploy.sh
script:
  - ./gradlew shadowJar --no-daemon -x autoLintGradle
after_success:
  - ./deploy.sh
  - ./gradlew jacocoTestReport -x autoLintGradle
  - bash <(curl -s https://codecov.io/bash)
