language: java
sudo: required
jdk:
  - oraclejdk8
services: docker
branches:
  only:
    - master
env:
  - TERM=dumb
after_success:
  - ./gradlew jacocoTestReport --no-daemon
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u nwillc -p ${DOCKER_PASSWD}
  - ./gradlew pushImage
