/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nwillc' at '10/6/15 11:00 PM' with Gradle 2.7
 *
 * @author nwillc, @date 10/6/15 11:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
